version: 2
jobs:
    build:
        docker:
          # specify the version you desire here
          - image: circleci/node:10.14   
        working_directory: ~/app
        steps:
          - checkout
          - setup_remote_docker:
               docker_layer_caching: true
          - run: git submodule sync --recursive
          - run: git submodule update --recursive --init
          - add_ssh_keys
          - run:
               name: Keyscan Github (HACK)
               command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          - run: docker build --rm=false -t rahul/test .
                        
                        
