version: 2
jobs:
    build:
        docker:
          # specify the version you desire here
          - image: circleci/node:10.14   
        working_directory: ~/app
        steps:
          - checkout
          - run: git submodule sync --recursive
          - run: git submodule update --recursive --init
          - run: 
                command: |
                        sudo apt-get update && sudo apt-get install python-pip libpython-dev
                        sudo pip install awscli
